---
kind: pipeline
name: dev
type: kubernetes
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    commands:
      - echo 'begin scan'
      - sonar-scanner -Dsonar.projectBaseDir=. -Dproject.settings=./sonar-project.properties
    settings:
      sonar_host: http://sonar.cityocean.com/
      sonar_token:
        from_secret: sonar
  - name: build-package
    image: node:latest
    commands:
      - npm install --legacy-peer-deps --registry=http://npm.dev.com 
      - npm run build:portal:dev  
  - name: ftp-upload-dev
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME: co
      FTP_PASSWORD:
        from_secret: dev-ftppsd
      PLUGIN_HOSTNAME: 192.168.4.42:21
      PLUGIN_SECURE: false
      PLUGIN_VERIFY: false
      PLUGIN_CHMOD: false
      PLUGIN_DEST_DIR: /
      PLUGIN_SRC_DIR: /dist/portal
     when:
      ref:
        - refs/heads/feature-*
        - refs/tags/**
      #PLUGIN_EXCLUDE: ^\.git/$
  - name: ftp-upload-test
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME: co
      FTP_PASSWORD:
        from_secret: test-ftppsd
      PLUGIN_HOSTNAME: 192.168.4.42:21
      PLUGIN_SECURE: false
      PLUGIN_VERIFY: false
      PLUGIN_CHMOD: false
      PLUGIN_DEST_DIR: /
      PLUGIN_SRC_DIR: /dist/portal
      #PLUGIN_EXCLUDE: ^\.git/$
    when:
      ref:
        - refs/heads/release-*
        - refs/tags/**
  - name: ftp-upload-prod
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME: devops
      FTP_PASSWORD:
        from_secret: prd-ftppsd
      PLUGIN_HOSTNAME: 47.107.133.59:20009
      PLUGIN_SECURE: false
      PLUGIN_VERIFY: false
      PLUGIN_CHMOD: false
      PLUGIN_DEST_DIR: /
      PLUGIN_SRC_DIR: /dist/portal
      #PLUGIN_EXCLUDE: ^\.git/$
    when:
      ref:
        - refs/heads/master
        - refs/tags/**
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
volumes:
  - name: cache
    host: 
      path: /home/cache
trigger:
  event:
  - tag

